import { Component, OnInit } from '@angular/core';
import {ActivatedRoute} from "@angular/router";
import {AngularFireDatabase} from "@angular/fire/compat/database";
import {MatDialog} from "@angular/material/dialog";
import {ApplicationDetailsComponent} from "../application-details/application-details.component";
import * as XLSX from 'xlsx';
import {ExcelService} from "../excel.service";
import {CommentsComponent} from "../comments/comments.component";

export interface Candidate{
  Affiliation: string;
  CV: string;
  Email: string;
  ['English Proficiency']: string;
  ['Expectations']: string;
  ['Future Contact']: string;
  ['Goals']: string;
  ['Name']: string;
  ['Phone']: string;
  ['Professional Background']: string;
  ['Topic in Life Science']: string;
  ['Experience with Users']: string;
  ['Supercomputers in Sweden and Germany']: string;
  Motivation: string;
  ['Willingness to Learn']: string;
}

@Component({
  selector: 'app-listing-candidates',
  templateUrl: './listing-candidates.component.html',
  styleUrls: ['./listing-candidates.component.css']
})

export class ListingCandidatesComponent implements OnInit {

  type: string = '';
  shortListText = 'Shortlist';
  jobTitle: string = '';
  candidateData: Array <any> = [
    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },
    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Supercomputers in Sweden and Germany']: '',
      Motivation: '',
      ['Willingness to Learn']: '',
    },
  ];
  shortlistedCandidates: any = [];
  rejectedCandidates: any = [];
  finalData: Array <any> = [];
  isShortListed = false;
  displayMessage = false;
  appKeys: any = [];
  isRejected = false;
  constructor(private route: ActivatedRoute, private db: AngularFireDatabase, private dialog: MatDialog, private excel: ExcelService) {
    route.params.subscribe(params =>{
      this.type = params['type'];
    });
  }

  ngOnInit(): void {
    this.db.list('Applications/' + this.type).valueChanges().subscribe(title => {
      // @ts-ignore
      this.jobTitle = title[4].toString();
    });
    this.db.list('Applications/' + this.type + '/wwww_Responses').snapshotChanges().subscribe(keys=> {
      for(let i = 0; i<keys.length; i++){
        this.appKeys.push(keys[i].key);
      }
      console.log(this.appKeys);
    });
    this.db.list('Applications/' + this.type + '/wwww_Responses').valueChanges().subscribe(res=>{
      if(res.length !=0){

        for (let i=0; i<res.length; i++){

          // @ts-ignore
          let k = Object.keys(res[i]);
          // @ts-ignore
          for(let j = 0; j<Object.keys(res[i]).length; j++){
            // @ts-ignore
            this.candidateData[i][k[j]] = res[i][k[j]];
          }
        }
        this.displayMessage =false;
      } else {
        this.displayMessage = true;
      }
      let kandidat = this.candidateData.slice(0, this.candidateData.length-1);
      kandidat.splice(res.length, this.candidateData.length-res.length);
      this.finalData = kandidat;

    });
    console.log(this.appKeys);
  }
  openApplication(index: number){
    this.dialog.open(ApplicationDetailsComponent, {
      width: '700px',
      data:{
        data: this.finalData[index]
      }
      }
    )
  }
  export(): void{
    this.excel.exportAsExcelFile(this.finalData, this.jobTitle);
  }
  shortlist(index: number) {
    if(this.finalData[index].isShortListed==undefined || this.finalData[index].isShortListed==false){
      this.shortlistedCandidates.push({
        Name: this.finalData[index].Name,
        Email: this.finalData[index].Email
      });
      this.finalData[index].isShortListed = true;
      this.db.database.ref('Applications/'+ this.type + '/wwww_Responses/' +this.appKeys[index]).update({
        isShortListed: true
      });
    }

    console.log(this.shortlistedCandidates);
  }
  removeFromShortList(index: number){
    if(this.finalData[index].isShortListed){
      this.finalData[index].isShortListed = false;
      this.shortlistedCandidates.splice(index, 1);
      this.db.database.ref('Applications/'+ this.type + '/wwww_Responses/' +this.appKeys[index]).update({
        isShortListed: false
      });
    }
  }
  exportShortList(): void{
    this.db.list('Applications/' + this.type + '/wwww_Responses', ref => {
      const k = ref.orderByChild('isShortListed').equalTo(true);
      return k;
    }).valueChanges().subscribe(shortlist => {
      this.shortlistedCandidates = shortlist;
    });
    this.excel.exportAsExcelFile(this.shortlistedCandidates, 'SHORTLIST_' + this.jobTitle);
  }
  openComments(index: number){
    this.dialog.open(CommentsComponent, {
      width: '500px',
      data: {
        index: this.appKeys[index],
        type: this.type
      }
    })
  }
  reject(index: number){
    if(this.finalData[index].isRejected==undefined || this.finalData[index].isRejected==false){
      this.rejectedCandidates.push({
        Name: this.finalData[index].Name,
        Email: this.finalData[index].Email
      });
      this.finalData[index].isRejected = true;
      this.db.database.ref('Applications/'+ this.type + '/wwww_Responses/' +this.appKeys[index]).update({
        isRejected: true
      });
    }
  }
  reverseReject(index: number){
    if(this.finalData[index].isRejected){
      this.finalData[index].isRejected = false;
      this.db.database.ref('Applications/'+ this.type + '/wwww_Responses/' +this.appKeys[index]).update({
        isRejected: false
      });
    }
  }
}
