import {AfterViewInit, Component, OnInit, ViewChild, ViewEncapsulation} from '@angular/core';
import {AngularFireDatabase} from "@angular/fire/compat/database";
import {MatDialog} from "@angular/material/dialog";
import {Router} from "@angular/router";
import {MatSort, Sort} from "@angular/material/sort";
import {MatTableDataSource} from "@angular/material/table";
import {LiveAnnouncer} from "@angular/cdk/a11y";
import {DatePipe} from "@angular/common";


@Component({
  selector: 'app-candidates',
  templateUrl: './candidates.component.html',
  styleUrls: ['./candidates.component.css'],
  encapsulation: ViewEncapsulation.None
})


export class CandidatesComponent implements OnInit, AfterViewInit {

  openPositions: Array <any> = [
    {listingTitle: '',
      jobTitle: '',
      appDeadline: '',
      description: '',
      employer: '',
      duration: '',
      format: '',
      qualifications: [],
      w_Image: '',
      w_Visible: false,
      wHours: '',
      wStatus: '',
      tasks: {},
      keys: [],
      renumeration: '',
      key: '',
      responses: {}},
    {listingTitle: '',
      jobTitle: '',
      appDeadline: 'DD/MM/YYYY',
      employer: 'ABI + a US-based company',
      duration: '6 months',
      format: 'paid internship',
      qualifications: ['Excellent knowledge of Molecular Biology/Molecular Genetics (priority) or Chemistry/Physics',
        'Basic programming and statistics skills',
        'Good writing/reporting skills',
        'High level of English proficiency',
        'Ability to learn quickly, easily read and comprehend scientific literature, motivation to learn bioinformatics',
        'Good communication skills',
        'Responsibility and time management'],
      w_Image: ''},
    {listingTitle: 'Systems biology analysis of liver metastases',
      jobTitle: 'Bioinformatics Researcher',
      appDeadline: 'DD/MM/YYYY',
      employer: 'ABI + a US-based company',
      duration: '6 months',
      format: 'paid internship',
      qualifications: ['Excellent knowledge of Molecular/Cancer Biology and Genomics',
        'Ability to read and comprehend scientific papers, extract data',
        'Experience with spreadsheet editors',
        'Beginner/intermediate programming skills in R (preferable) or Python',
        'Desired familiarity with genomic databases (NCBI, UCSC,GEO)']},
    {listingTitle: 'Linux System Administrator',
      jobTitle: 'System Administrator',
      appDeadline: 'DD/MM/YYYY',
      employer: 'ABI + a US-based company',
      format: 'part-time/full-time',
      qualifications: ['Experience working with Linux OS, command-line and shell',
        'Experience with installation of software for various user groups',
        'Experience with SLURM resource distribution system',
        'Good command of English',
        'Good communication skills']},
    {listingTitle: 'Linux System Administrator',
      jobTitle: 'System Administrator',
      appDeadline: 'DD/MM/YYYY',
      employer: 'ABI + a US-based company',
      format: 'part-time/full-time',
      qualifications: ['Experience working with Linux OS, command-line and shell',
        'Experience with installation of software for various user groups',
        'Experience with SLURM resource distribution system',
        'Good command of English',
        'Good communication skills']},
    {listingTitle: 'Linux System Administrator',
      jobTitle: 'System Administrator',
      appDeadline: 'DD/MM/YYYY',
      employer: 'ABI + a US-based company',
      format: 'part-time/full-time',
      qualifications: ['Experience working with Linux OS, command-line and shell',
        'Experience with installation of software for various user groups',
        'Experience with SLURM resource distribution system',
        'Good command of English',
        'Good communication skills']},
    {listingTitle: 'Linux System Administrator',
      jobTitle: 'System Administrator',
      appDeadline: 'DD/MM/YYYY',
      employer: 'ABI + a US-based company',
      format: 'part-time/full-time',
      qualifications: ['Experience working with Linux OS, command-line and shell',
        'Experience with installation of software for various user groups',
        'Experience with SLURM resource distribution system',
        'Good command of English',
        'Good communication skills']},
    {listingTitle: 'Linux System Administrator',
      jobTitle: 'System Administrator',
      appDeadline: 'DD/MM/YYYY',
      employer: 'ABI + a US-based company',
      format: 'part-time/full-time',
      qualifications: ['Experience working with Linux OS, command-line and shell',
        'Experience with installation of software for various user groups',
        'Experience with SLURM resource distribution system',
        'Good command of English',
        'Good communication skills']},
    {listingTitle: 'Linux System Administrator',
      jobTitle: 'System Administrator',
      appDeadline: 'DD/MM/YYYY',
      employer: 'ABI + a US-based company',
      format: 'part-time/full-time',
      qualifications: ['Experience working with Linux OS, command-line and shell',
        'Experience with installation of software for various user groups',
        'Experience with SLURM resource distribution system',
        'Good command of English',
        'Good communication skills']},
    {listingTitle: 'Linux System Administrator',
      jobTitle: 'System Administrator',
      appDeadline: 'DD/MM/YYYY',
      employer: 'ABI + a US-based company',
      format: 'part-time/full-time',
      qualifications: ['Experience working with Linux OS, command-line and shell',
        'Experience with installation of software for various user groups',
        'Experience with SLURM resource distribution system',
        'Good command of English',
        'Good communication skills']},
    {listingTitle: 'Linux System Administrator',
      jobTitle: 'System Administrator',
      appDeadline: 'DD/MM/YYYY',
      employer: 'ABI + a US-based company',
      format: 'part-time/full-time',
      qualifications: ['Experience working with Linux OS, command-line and shell',
        'Experience with installation of software for various user groups',
        'Experience with SLURM resource distribution system',
        'Good command of English',
        'Good communication skills']},
    {listingTitle: 'Linux System Administrator',
      jobTitle: 'System Administrator',
      appDeadline: 'DD/MM/YYYY',
      employer: 'ABI + a US-based company',
      format: 'part-time/full-time',
      qualifications: ['Experience working with Linux OS, command-line and shell',
        'Experience with installation of software for various user groups',
        'Experience with SLURM resource distribution system',
        'Good command of English',
        'Good communication skills']},
    {listingTitle: 'Linux System Administrator',
      jobTitle: 'System Administrator',
      appDeadline: 'DD/MM/YYYY',
      employer: 'ABI + a US-based company',
      format: 'part-time/full-time',
      qualifications: ['Experience working with Linux OS, command-line and shell',
        'Experience with installation of software for various user groups',
        'Experience with SLURM resource distribution system',
        'Good command of English',
        'Good communication skills']},
    {listingTitle: 'Linux System Administrator',
      jobTitle: 'System Administrator',
      appDeadline: 'DD/MM/YYYY',
      employer: 'ABI + a US-based company',
      format: 'part-time/full-time',
      qualifications: ['Experience working with Linux OS, command-line and shell',
        'Experience with installation of software for various user groups',
        'Experience with SLURM resource distribution system',
        'Good command of English',
        'Good communication skills']},
    {listingTitle: 'Linux System Administrator',
      jobTitle: 'System Administrator',
      appDeadline: 'DD/MM/YYYY',
      employer: 'ABI + a US-based company',
      format: 'part-time/full-time',
      qualifications: ['Experience working with Linux OS, command-line and shell',
        'Experience with installation of software for various user groups',
        'Experience with SLURM resource distribution system',
        'Good command of English',
        'Good communication skills']},
    {listingTitle: 'Linux System Administrator',
      jobTitle: 'System Administrator',
      appDeadline: 'DD/MM/YYYY',
      employer: 'ABI + a US-based company',
      format: 'part-time/full-time',
      qualifications: ['Experience working with Linux OS, command-line and shell',
        'Experience with installation of software for various user groups',
        'Experience with SLURM resource distribution system',
        'Good command of English',
        'Good communication skills']},
    {listingTitle: 'Linux System Administrator',
      jobTitle: 'System Administrator',
      appDeadline: 'DD/MM/YYYY',
      employer: 'ABI + a US-based company',
      format: 'part-time/full-time',
      qualifications: ['Experience working with Linux OS, command-line and shell',
        'Experience with installation of software for various user groups',
        'Experience with SLURM resource distribution system',
        'Good command of English',
        'Good communication skills']},
    {listingTitle: 'Linux System Administrator',
      jobTitle: 'System Administrator',
      appDeadline: 'DD/MM/YYYY',
      employer: 'ABI + a US-based company',
      format: 'part-time/full-time',
      qualifications: ['Experience working with Linux OS, command-line and shell',
        'Experience with installation of software for various user groups',
        'Experience with SLURM resource distribution system',
        'Good command of English',
        'Good communication skills']},
    {listingTitle: 'Linux System Administrator',
      jobTitle: 'System Administrator',
      appDeadline: 'DD/MM/YYYY',
      employer: 'ABI + a US-based company',
      format: 'part-time/full-time',
      qualifications: ['Experience working with Linux OS, command-line and shell',
        'Experience with installation of software for various user groups',
        'Experience with SLURM resource distribution system',
        'Good command of English',
        'Good communication skills']},
    {listingTitle: 'Linux System Administrator',
      jobTitle: 'System Administrator',
      appDeadline: 'DD/MM/YYYY',
      employer: 'ABI + a US-based company',
      format: 'part-time/full-time',
      qualifications: ['Experience working with Linux OS, command-line and shell',
        'Experience with installation of software for various user groups',
        'Experience with SLURM resource distribution system',
        'Good command of English',
        'Good communication skills']},
    {listingTitle: 'Linux System Administrator',
      jobTitle: 'System Administrator',
      appDeadline: 'DD/MM/YYYY',
      employer: 'ABI + a US-based company',
      format: 'part-time/full-time',
      qualifications: ['Experience working with Linux OS, command-line and shell',
        'Experience with installation of software for various user groups',
        'Experience with SLURM resource distribution system',
        'Good command of English',
        'Good communication skills']},
    {listingTitle: 'Linux System Administrator',
      jobTitle: 'System Administrator',
      appDeadline: 'DD/MM/YYYY',
      employer: 'ABI + a US-based company',
      format: 'part-time/full-time',
      qualifications: ['Experience working with Linux OS, command-line and shell',
        'Experience with installation of software for various user groups',
        'Experience with SLURM resource distribution system',
        'Good command of English',
        'Good communication skills']},
    {listingTitle: 'Linux System Administrator',
      jobTitle: 'System Administrator',
      appDeadline: 'DD/MM/YYYY',
      employer: 'ABI + a US-based company',
      format: 'part-time/full-time',
      qualifications: ['Experience working with Linux OS, command-line and shell',
        'Experience with installation of software for various user groups',
        'Experience with SLURM resource distribution system',
        'Good command of English',
        'Good communication skills']},
    {listingTitle: 'Linux System Administrator',
      jobTitle: 'System Administrator',
      appDeadline: 'DD/MM/YYYY',
      employer: 'ABI + a US-based company',
      format: 'part-time/full-time',
      qualifications: ['Experience working with Linux OS, command-line and shell',
        'Experience with installation of software for various user groups',
        'Experience with SLURM resource distribution system',
        'Good command of English',
        'Good communication skills']},
    {listingTitle: 'Linux System Administrator',
      jobTitle: 'System Administrator',
      appDeadline: 'DD/MM/YYYY',
      employer: 'ABI + a US-based company',
      format: 'part-time/full-time',
      qualifications: ['Experience working with Linux OS, command-line and shell',
        'Experience with installation of software for various user groups',
        'Experience with SLURM resource distribution system',
        'Good command of English',
        'Good communication skills']},
    {listingTitle: 'Linux System Administrator',
      jobTitle: 'System Administrator',
      appDeadline: 'DD/MM/YYYY',
      employer: 'ABI + a US-based company',
      format: 'part-time/full-time',
      qualifications: ['Experience working with Linux OS, command-line and shell',
        'Experience with installation of software for various user groups',
        'Experience with SLURM resource distribution system',
        'Good command of English',
        'Good communication skills']},
    {listingTitle: 'Linux System Administrator',
      jobTitle: 'System Administrator',
      appDeadline: 'DD/MM/YYYY',
      employer: 'ABI + a US-based company',
      format: 'part-time/full-time',
      qualifications: ['Experience working with Linux OS, command-line and shell',
        'Experience with installation of software for various user groups',
        'Experience with SLURM resource distribution system',
        'Good command of English',
        'Good communication skills']},
    {listingTitle: 'Linux System Administrator',
      jobTitle: 'System Administrator',
      appDeadline: 'DD/MM/YYYY',
      employer: 'ABI + a US-based company',
      format: 'part-time/full-time',
      qualifications: ['Experience working with Linux OS, command-line and shell',
        'Experience with installation of software for various user groups',
        'Experience with SLURM resource distribution system',
        'Good command of English',
        'Good communication skills']},
    {listingTitle: 'Linux System Administrator',
      jobTitle: 'System Administrator',
      appDeadline: 'DD/MM/YYYY',
      employer: 'ABI + a US-based company',
      format: 'part-time/full-time',
      qualifications: ['Experience working with Linux OS, command-line and shell',
        'Experience with installation of software for various user groups',
        'Experience with SLURM resource distribution system',
        'Good command of English',
        'Good communication skills']},
    {listingTitle: 'Linux System Administrator',
      jobTitle: 'System Administrator',
      appDeadline: 'DD/MM/YYYY',
      employer: 'ABI + a US-based company',
      format: 'part-time/full-time',
      qualifications: ['Experience working with Linux OS, command-line and shell',
        'Experience with installation of software for various user groups',
        'Experience with SLURM resource distribution system',
        'Good command of English',
        'Good communication skills']},
    {listingTitle: 'Linux System Administrator',
      jobTitle: 'System Administrator',
      appDeadline: 'DD/MM/YYYY',
      employer: 'ABI + a US-based company',
      format: 'part-time/full-time',
      qualifications: ['Experience working with Linux OS, command-line and shell',
        'Experience with installation of software for various user groups',
        'Experience with SLURM resource distribution system',
        'Good command of English',
        'Good communication skills']},
    {listingTitle: 'Linux System Administrator',
      jobTitle: 'System Administrator',
      appDeadline: 'DD/MM/YYYY',
      employer: 'ABI + a US-based company',
      format: 'part-time/full-time',
      qualifications: ['Experience working with Linux OS, command-line and shell',
        'Experience with installation of software for various user groups',
        'Experience with SLURM resource distribution system',
        'Good command of English',
        'Good communication skills']},
    {listingTitle: 'Linux System Administrator',
      jobTitle: 'System Administrator',
      appDeadline: 'DD/MM/YYYY',
      employer: 'ABI + a US-based company',
      format: 'part-time/full-time',
      qualifications: ['Experience working with Linux OS, command-line and shell',
        'Experience with installation of software for various user groups',
        'Experience with SLURM resource distribution system',
        'Good command of English',
        'Good communication skills']},
    {listingTitle: 'Linux System Administrator',
      jobTitle: 'System Administrator',
      appDeadline: 'DD/MM/YYYY',
      employer: 'ABI + a US-based company',
      format: 'part-time/full-time',
      qualifications: ['Experience working with Linux OS, command-line and shell',
        'Experience with installation of software for various user groups',
        'Experience with SLURM resource distribution system',
        'Good command of English',
        'Good communication skills']},
    {listingTitle: 'Linux System Administrator',
      jobTitle: 'System Administrator',
      appDeadline: 'DD/MM/YYYY',
      employer: 'ABI + a US-based company',
      format: 'part-time/full-time',
      qualifications: ['Experience working with Linux OS, command-line and shell',
        'Experience with installation of software for various user groups',
        'Experience with SLURM resource distribution system',
        'Good command of English',
        'Good communication skills']},
    {listingTitle: 'Linux System Administrator',
      jobTitle: 'System Administrator',
      appDeadline: 'DD/MM/YYYY',
      employer: 'ABI + a US-based company',
      format: 'part-time/full-time',
      qualifications: ['Experience working with Linux OS, command-line and shell',
        'Experience with installation of software for various user groups',
        'Experience with SLURM resource distribution system',
        'Good command of English',
        'Good communication skills']},
    {listingTitle: 'Linux System Administrator',
      jobTitle: 'System Administrator',
      appDeadline: 'DD/MM/YYYY',
      employer: 'ABI + a US-based company',
      format: 'part-time/full-time',
      qualifications: ['Experience working with Linux OS, command-line and shell',
        'Experience with installation of software for various user groups',
        'Experience with SLURM resource distribution system',
        'Good command of English',
        'Good communication skills']},
    {listingTitle: 'Linux System Administrator',
      jobTitle: 'System Administrator',
      appDeadline: 'DD/MM/YYYY',
      employer: 'ABI + a US-based company',
      format: 'part-time/full-time',
      qualifications: ['Experience working with Linux OS, command-line and shell',
        'Experience with installation of software for various user groups',
        'Experience with SLURM resource distribution system',
        'Good command of English',
        'Good communication skills']},
    {listingTitle: 'Linux System Administrator',
      jobTitle: 'System Administrator',
      appDeadline: 'DD/MM/YYYY',
      employer: 'ABI + a US-based company',
      format: 'part-time/full-time',
      qualifications: ['Experience working with Linux OS, command-line and shell',
        'Experience with installation of software for various user groups',
        'Experience with SLURM resource distribution system',
        'Good command of English',
        'Good communication skills']},
    {listingTitle: 'Linux System Administrator',
      jobTitle: 'System Administrator',
      appDeadline: 'DD/MM/YYYY',
      employer: 'ABI + a US-based company',
      format: 'part-time/full-time',
      qualifications: ['Experience working with Linux OS, command-line and shell',
        'Experience with installation of software for various user groups',
        'Experience with SLURM resource distribution system',
        'Good command of English',
        'Good communication skills']},
    {listingTitle: 'Linux System Administrator',
      jobTitle: 'System Administrator',
      appDeadline: 'DD/MM/YYYY',
      employer: 'ABI + a US-based company',
      format: 'part-time/full-time',
      qualifications: ['Experience working with Linux OS, command-line and shell',
        'Experience with installation of software for various user groups',
        'Experience with SLURM resource distribution system',
        'Good command of English',
        'Good communication skills']},
    {listingTitle: 'Linux System Administrator',
      jobTitle: 'System Administrator',
      appDeadline: 'DD/MM/YYYY',
      employer: 'ABI + a US-based company',
      format: 'part-time/full-time',
      qualifications: ['Experience working with Linux OS, command-line and shell',
        'Experience with installation of software for various user groups',
        'Experience with SLURM resource distribution system',
        'Good command of English',
        'Good communication skills']},
    {listingTitle: 'Linux System Administrator',
      jobTitle: 'System Administrator',
      appDeadline: 'DD/MM/YYYY',
      employer: 'ABI + a US-based company',
      format: 'part-time/full-time',
      qualifications: ['Experience working with Linux OS, command-line and shell',
        'Experience with installation of software for various user groups',
        'Experience with SLURM resource distribution system',
        'Good command of English',
        'Good communication skills']},
    {listingTitle: 'Linux System Administrator',
      jobTitle: 'System Administrator',
      appDeadline: 'DD/MM/YYYY',
      employer: 'ABI + a US-based company',
      format: 'part-time/full-time',
      qualifications: ['Experience working with Linux OS, command-line and shell',
        'Experience with installation of software for various user groups',
        'Experience with SLURM resource distribution system',
        'Good command of English',
        'Good communication skills']},
    {listingTitle: 'Linux System Administrator',
      jobTitle: 'System Administrator',
      appDeadline: 'DD/MM/YYYY',
      employer: 'ABI + a US-based company',
      format: 'part-time/full-time',
      qualifications: ['Experience working with Linux OS, command-line and shell',
        'Experience with installation of software for various user groups',
        'Experience with SLURM resource distribution system',
        'Good command of English',
        'Good communication skills']},
    {listingTitle: 'Linux System Administrator',
      jobTitle: 'System Administrator',
      appDeadline: 'DD/MM/YYYY',
      employer: 'ABI + a US-based company',
      format: 'part-time/full-time',
      qualifications: ['Experience working with Linux OS, command-line and shell',
        'Experience with installation of software for various user groups',
        'Experience with SLURM resource distribution system',
        'Good command of English',
        'Good communication skills']},
    {listingTitle: 'Linux System Administrator',
      jobTitle: 'System Administrator',
      appDeadline: 'DD/MM/YYYY',
      employer: 'ABI + a US-based company',
      format: 'part-time/full-time',
      qualifications: ['Experience working with Linux OS, command-line and shell',
        'Experience with installation of software for various user groups',
        'Experience with SLURM resource distribution system',
        'Good command of English',
        'Good communication skills']},
    {listingTitle: 'Linux System Administrator',
      jobTitle: 'System Administrator',
      appDeadline: 'DD/MM/YYYY',
      employer: 'ABI + a US-based company',
      format: 'part-time/full-time',
      qualifications: ['Experience working with Linux OS, command-line and shell',
        'Experience with installation of software for various user groups',
        'Experience with SLURM resource distribution system',
        'Good command of English',
        'Good communication skills']},
    {listingTitle: 'Linux System Administrator',
      jobTitle: 'System Administrator',
      appDeadline: 'DD/MM/YYYY',
      employer: 'ABI + a US-based company',
      format: 'part-time/full-time',
      qualifications: ['Experience working with Linux OS, command-line and shell',
        'Experience with installation of software for various user groups',
        'Experience with SLURM resource distribution system',
        'Good command of English',
        'Good communication skills']},
    {listingTitle: 'Linux System Administrator',
      jobTitle: 'System Administrator',
      appDeadline: 'DD/MM/YYYY',
      employer: 'ABI + a US-based company',
      format: 'part-time/full-time',
      qualifications: ['Experience working with Linux OS, command-line and shell',
        'Experience with installation of software for various user groups',
        'Experience with SLURM resource distribution system',
        'Good command of English',
        'Good communication skills']},
    {listingTitle: 'Linux System Administrator',
      jobTitle: 'System Administrator',
      appDeadline: 'DD/MM/YYYY',
      employer: 'ABI + a US-based company',
      format: 'part-time/full-time',
      qualifications: ['Experience working with Linux OS, command-line and shell',
        'Experience with installation of software for various user groups',
        'Experience with SLURM resource distribution system',
        'Good command of English',
        'Good communication skills']},
    {listingTitle: 'Linux System Administrator',
      jobTitle: 'System Administrator',
      appDeadline: 'DD/MM/YYYY',
      employer: 'ABI + a US-based company',
      format: 'part-time/full-time',
      qualifications: ['Experience working with Linux OS, command-line and shell',
        'Experience with installation of software for various user groups',
        'Experience with SLURM resource distribution system',
        'Good command of English',
        'Good communication skills']},
    {listingTitle: 'Linux System Administrator',
      jobTitle: 'System Administrator',
      appDeadline: 'DD/MM/YYYY',
      employer: 'ABI + a US-based company',
      format: 'part-time/full-time',
      qualifications: ['Experience working with Linux OS, command-line and shell',
        'Experience with installation of software for various user groups',
        'Experience with SLURM resource distribution system',
        'Good command of English',
        'Good communication skills']},
    {listingTitle: 'Linux System Administrator',
      jobTitle: 'System Administrator',
      appDeadline: 'DD/MM/YYYY',
      employer: 'ABI + a US-based company',
      format: 'part-time/full-time',
      qualifications: ['Experience working with Linux OS, command-line and shell',
        'Experience with installation of software for various user groups',
        'Experience with SLURM resource distribution system',
        'Good command of English',
        'Good communication skills']},
    {listingTitle: 'Linux System Administrator',
      jobTitle: 'System Administrator',
      appDeadline: 'DD/MM/YYYY',
      employer: 'ABI + a US-based company',
      format: 'part-time/full-time',
      qualifications: ['Experience working with Linux OS, command-line and shell',
        'Experience with installation of software for various user groups',
        'Experience with SLURM resource distribution system',
        'Good command of English',
        'Good communication skills']},
    {listingTitle: 'Linux System Administrator',
      jobTitle: 'System Administrator',
      appDeadline: 'DD/MM/YYYY',
      employer: 'ABI + a US-based company',
      format: 'part-time/full-time',
      qualifications: ['Experience working with Linux OS, command-line and shell',
        'Experience with installation of software for various user groups',
        'Experience with SLURM resource distribution system',
        'Good command of English',
        'Good communication skills']},
    {listingTitle: 'Linux System Administrator',
      jobTitle: 'System Administrator',
      appDeadline: 'DD/MM/YYYY',
      employer: 'ABI + a US-based company',
      format: 'part-time/full-time',
      qualifications: ['Experience working with Linux OS, command-line and shell',
        'Experience with installation of software for various user groups',
        'Experience with SLURM resource distribution system',
        'Good command of English',
        'Good communication skills']},
    {listingTitle: 'Linux System Administrator',
      jobTitle: 'System Administrator',
      appDeadline: 'DD/MM/YYYY',
      employer: 'ABI + a US-based company',
      format: 'part-time/full-time',
      qualifications: ['Experience working with Linux OS, command-line and shell',
        'Experience with installation of software for various user groups',
        'Experience with SLURM resource distribution system',
        'Good command of English',
        'Good communication skills']},
  ];
  keyArray = [];
  applicantNumber: Array<any> = [];
  candidateData: Array <any> = [
    {
    Affiliation: '',
    CV: '',
    Email: '',
    ['English Proficiency']: '',
    ['Expectations']: '',
    ['Future Contact']: '',
    ['Goals']: '',
    ['Name']: '',
    ['Phone']: '',
    ['Professional Background']: '',
    ['Topic in Life Science']: '',
    ['Time Availability']: '',
    ['Your Mind']: '',
    },
    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },
    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },
    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },
    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },
    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },
    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },
    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },
    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },
    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },
    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },
    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },
    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },
    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },
    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },
    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },
    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },
    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },
    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },
    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },
    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },
    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },
    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },
    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },
    {
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },{
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },{
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },{
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },{
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },{
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },{
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },{
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },{
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },{
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },{
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },{
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },{
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },{
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },{
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },{
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },{
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },{
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },{
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },{
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },{
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },{
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },{
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },{
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },{
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },{
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },{
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },{
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },{
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },{
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },{
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },{
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },{
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },{
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },{
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },{
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },{
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },{
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },{
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },{
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },{
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },{
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },{
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },{
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },{
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },{
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },{
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },{
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },{
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },{
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },{
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },{
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },{
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },{
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },{
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },{
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },{
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },{
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },{
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },{
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },{
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },{
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },{
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },{
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },{
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },{
      Affiliation: '',
      CV: '',
      Email: '',
      ['English Proficiency']: '',
      ['Expectations']: '',
      ['Future Contact']: '',
      ['Goals']: '',
      ['Name']: '',
      ['Phone']: '',
      ['Professional Background']: '',
      ['Topic in Life Science']: '',
      ['Time Availability']: '',
      ['Your Mind']: '',
    },
  ];
  finalData: Array <any> = [];
  displayMessage = false;
  currentDate: string = '';
  displayedColumns: string[] = ['number', 'jobTitle', 'listingTitle', 'appDeadline', 'numApp', 'button'];
  dataSource = new MatTableDataSource(this.openPositions);
  constructor(private db: AngularFireDatabase, private dialog: MatDialog, private router: Router, private _liveAnnouncer: LiveAnnouncer, public datepipe: DatePipe) {

  }
  // @ts-ignore
  @ViewChild(MatSort) sort: MatSort;
  ngOnInit(): void {
    var currentDate = new Date();
    this.currentDate = ("0"+currentDate.getDate()).slice(-2) + "/" + ("0"+(currentDate.getMonth() + 1)).slice(-2) + "/" + currentDate.getFullYear();
    this.db.list('Applications').snapshotChanges().subscribe(res => {
      for (let i=0; i<res.length; i++){
        // @ts-ignore
        this.keyArray.push(res[i].key);
      }
      this.keyArray.reverse();
      this.db.list('Applications').valueChanges().subscribe(res=>{
        for(let i = 0; i<res.length; i++){
          // @ts-ignore
          this.db.list('Applications/' + this.keyArray[i].toString()).valueChanges()
            .subscribe((val: Array<any>)=> {
              // @ts-ignore
              this.openPositions[i].appDeadline = val[0].toString();
              // @ts-ignore
              this.openPositions[i].duration = val[1].toString();
              // @ts-ignore
              this.openPositions[i].employer = val[2].toString();
              // @ts-ignore
              this.openPositions[i].format = val[3].toString();
              // @ts-ignore
              this.openPositions[i].jobTitle = val[4];
              // @ts-ignore
              this.openPositions[i].listingTitle = val[5];
              // @ts-ignore
              this.openPositions[i].qualifications = val[6];
              // @ts-ignore
              this.openPositions[i].w_Image = val[8];
              // @ts-ignore
              this.openPositions[i].w_Visible = val[9];
              // @ts-ignore
              this.openPositions[i].wHours = val[7];
              // @ts-ignore
              this.openPositions[i].description = val[10];
              // @ts-ignore
              this.openPositions[i].wStatus = val[11];
              // @ts-ignore
              this.openPositions[i].tasks = val[12];
              // @ts-ignore
              this.openPositions[i].renumeration = val[13];
              // @ts-ignore
              this.openPositions[i].responses = val[14];
              if(val[14]){
                this.applicantNumber.push(Object.keys(val[14]).length)
              } else {
                this.applicantNumber.push(0);
              }

            });
        }
        this.dataSource = new MatTableDataSource(this.openPositions);
        let kandidat = this.openPositions.splice(res.length, this.openPositions.length-res.length);
        console.log(kandidat);
      });

    });
  }
  convertToDate (d: string) {
    // const [day, month, year] = d.split("/");
    //     // return new Date(Number(year), Number(month) - 1, Number(day));
    const [day, month, year] = d.split('/');
    const result = [year, month, day].join();
    return result;
  }
  ngAfterViewInit() {
    this.dataSource.sort = this.sort;
    // @ts-ignore
    console.log(this.datepipe.transform(new Date(), 'yyyyMMdd').toString() > '20220116');
    console.log(this.currentDate)
  }
  announceSortChange(sortState: Sort) {
    if (sortState.direction) {
      this._liveAnnouncer.announce(`Sorted ${sortState.direction}ending`);
    } else {
      this._liveAnnouncer.announce('Sorting cleared');
    }
  }
    openCandidateList(idx: number){
       this.db.list('Applications/' + this.keyArray[idx] + '/wwww_Responses').valueChanges().subscribe(res=>{
         if(res.length ==0){
            this.displayMessage = true;
         } else{
            this.displayMessage = false;
         }
       });
        this.router.navigate(['candidates/' + this.keyArray[idx]]);
  }

}
